paths:
  /api/products:
    get:
      summary: Get the products
      tags:
        - Products
      responses:
      "200":
      description: Successfull operation
      content:
      aplication/json:
      schema:
      type: array
    security:
      -bearerAuth: ["PREMIUM", "ADMIN"]
    post:
      summary: Create a new product
      tags:
        - Products
      requestBody:
      required: true
      content:
      aplication/json:
      
